name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    name: Danger Linting
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Ruby 
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Cache Rubygems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Danger Linting
      uses: MeilCli/danger-action@v5
      with:
        plugins_file: Gemfile
        install_path: vendor/bundle
        danger_file: Dangerfile
        danger_id: danger-pr
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Install Dependencies
      run: yarn install

    - name: Run Tests
      run: yarn test
